//
// Generated file, do not edit! Created by nedtool 5.4 from managers/execution/BootComplete.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __BOOTCOMPLETE_M_H
#define __BOOTCOMPLETE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>managers/execution/BootComplete.msg:16</tt> by nedtool.
 * <pre>
 * message BootComplete
 * {
 *     int moduleId;
 * }
 * </pre>
 */
class BootComplete : public ::omnetpp::cMessage
{
  protected:
    int moduleId;

  private:
    void copy(const BootComplete& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BootComplete&);

  public:
    BootComplete(const char *name=nullptr, short kind=0);
    BootComplete(const BootComplete& other);
    virtual ~BootComplete();
    BootComplete& operator=(const BootComplete& other);
    virtual BootComplete *dup() const override {return new BootComplete(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getModuleId() const;
    virtual void setModuleId(int moduleId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BootComplete& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BootComplete& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BOOTCOMPLETE_M_H

